#!/usr/bin/env python3

import sys
from argparse import ArgumentParser
import subprocess

import pandas as pd


def main():
    parser = ArgumentParser()
    cmds = ['trim', 'map', 'filter', 'join', 'plot', 'report']
    parser.add_argument("cmd", choices=cmds)
    parser.add_argument("annotation")
    args = parser.parse_args()

    df = pd.read_csv(args.annotation)

    df = df.query("toggle == 1")

    for i, sample in df.iterrows():
        print(f"Doing sample {sample['sample_name']}")
        cmd = f"make {args.cmd} "
        cmd += f"RUN_NAME={sample['sample_name']} "
        cmd += f"FLOWCELL={sample['flowcell']} "
        cmd += f"N_LANES={int(sample['nlanes'])} "
        cmd += f"N_BARCODES={int(sample['nbarcodes'])} "
        cmd += f"ANNOTATION={sample['annotation']} "
        cmd += f"VARIABLES={sample['variables']} "
        cmd += f"SPECIES_MIXING={int(sample['species_mixing'])}"
        if not pd.isnull(sample['expected_cell_number']):
            cmd += f"EXPECTED_CELL_NUMBER={int(sample['expected_cell_number'])}"
        print(cmd)
        subprocess.Popen(cmd.split(" "))


if __name__ == "__main__":
    sys.exit(main())
